#!/bin/bash

# Because Git submodule commands cannot operate without a work tree, they must
# be run from within $HOME (assuming this is the root of your dotfiles)
cd "$HOME"

# echo "Init submodules"
# yadm submodule update --recursive --init

system_type=$(uname -s)

# set up symlinks for windows
if [[ "$(uname -o)" = "Msys" ]]; then
  echo "Configuring windows"
  system_type=$(uname -o)
  export MSYS=winsymlinks:nativestrict
fi

# set up nushell configs
if command -v nu; then
  echo "Configuring nushell"
  nu_cfg_dir=$(nu -c '$nu.default-config-dir')
  nu -c 'mkdir $nu.default-config-dir'
  cfg_path=$(nu -c '[($nu.default-config-dir) "config.nu"] | path join')
  [[ -L "$cfg_path" ]] && unlink "$cfg_path"
  [[ -e "$cfg_path" ]] && mv "$cfg_path" "$cfg_path.bak"
  ln -s "$HOME/.config/nushell/config.nu" "$cfg_path"
fi

# only set up zgenon if zsh is available
if command -v zsh; then
  if [ ! -d "$HOME/.zgenom" ] || [ ! -d "$HOME/.zgenom/.git" ]; then
    echo "Configuring zgenom"
    mkdir -p $HOME/.zgenom
    cd $HOME/.zgenom
    git clone https://github.com/jandamm/zgenom.git .
  fi
fi

if [ "$system_type" = "Darwin" ]; then
  echo "Configuring macOS"
  # install homebrew if it's missing
  if ! command -v brew > /dev/null 2>&1; then
    echo "Installing homebrew"
    /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
  fi

  if [ -f "$HOME/.Brewfile" ]; then
    echo "Updating homebrew bundle"
    brew bundle --global
  fi

fi
